### ISSUE TITLE
Recipe conflict

### ISSUE THREAD

**Issue by Zero9o1o** [ZeekDaGeek/worldworldpack-public#1]
Iron constuction blocks have a recipe conflict with relocator

**Comment by ZeekDaGeek** [comment]
Temporary fix: User the Intellegent Workbench from RemoteIO, it'll allow you to solve conflicts.

**Comment by Thorton101** [comment]
Hi there,

I'm using this Pack for about a week and found several recipe problems, the bronze paxel from mekanism tools isn't craftable and the bronze sword in the crafting grid tries to build the thermal expansion version instead of the mekanism one. 
Is this intended, cause the NEI shows this items as craftable.

Best regards
Thorton

**Comment by xXTheBigBearXx** [comment]
Thorton, as stated above, use the Intelligent Workbench from Remote IO as a temporary fix
